name: My First GitHub Action # This GitHub Action runs a simple Python script and prints the output. 

on:
  issues:
    types: [opened, edited, reopened]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests__build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv pip install . --system --no-cache-dir

    - name: Run ruff
      run: uv run ruff check --fix .
        
    - name: Test script
      run: uv run pytest

    # - name: Docker build
    #   run: |
    #     docker build -t my-python-app .
    #     docker run my-python-app

