# .github/workflows/reusable-checks.yml
name: Reusable Python CI

on:
  workflow_call:  # Make it reusable

jobs:
  tests__build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv pip install . --system --no-cache-dir

      - name: Run ruff
        run: uv run ruff check --fix .

      - name: Test script
        run: uv run pytest

      - name: Build Docker image
        run: docker build -t my-docker-app .
